version: '3.3'

services:
  kontaktregister-statistikk-klient:
    image: difi/kontaktregister-statistikk-klient:${VERSION}
    ports:
      - "8084:8080"
    configs:
      - source: kontaktregister-statistikk-klient
        target: /application.properties
    secrets:
      - source: kontaktregister-statistikk-klient_ingest-password
        target: krr-stat-pumba
    networks:
      - statistics

networks:
  statistics:
    external: true

secrets:
  kontaktregister-statistikk-klient_ingest-password:
    external: true

configs:
  kontaktregister-statistikk-klient:
    external: true

